### ISSUE TITLE
User Story #8: As a user, I want to have my own profile page that displays my images

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#20]
Priority: High
Risk: Low
Story Points: 8

## Description
"As a user, I want to have my own profile page with all the content that I posted being displayed"
### User profile page
* Add a component containing the profile information of the user (name, and follows)
* Add follow button
* Add a grid component with all of the user's posted images

### Routing
* Add a route for each user (i.e. example.com/user/GryPr) - when going to a "wildcard" route, send a fetch request to the API to determine if the user exists
* Each route generates a page specific to the user based on their user data (each user page is different)

### Links to the user profile
* Add link to the user's own profile in the navigation bar
* Add link to the image box component that links to the image poster's page

## Tasks
#43 - Implement page routing
#31 #24 - Navigation bar leading to the user page

## Acceptance Test
- Under each image, there is a link to go to a user's profile page
- When clicked on the link, the local user is redirected to a user's profile page
- On the user's profile page, a list of images posted by the user is displayed

**Comment by salehatrq** [comment]
02-03-21
- Layout and design of the user profile page
- Link the images posted on the main feed to the user page
