### ISSUE TITLE
Integrate MSAL.js into React (Add login/logout)

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#26]
Sub-issue of #14

Add a login/signup button that leverages MSAL.js to redirect the user to Azure AD B2C, and allows the user to login or signup. Obtain the access token that will be used to authenticate all calls to the backend.

Example projects:
https://github.com/GryPr/next-experiments
https://github.com/GryPr/react-experiments
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample

**Comment by ChristopherKhoury** [comment]
Added components folder with authentication button as well as the authconfig.ts file in the Constants folder.
