### ISSUE TITLE
User Story #5: As a user, I want to follow other users

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#30]
Priority: Medium
Risk: Low
Story Points: 13

## Description

The user should be able to follow other users, and increment the other user's follower count

## Steps
- Add follow button to each user
- Add unfollow button if the user is already followed
- Add follower count

## Tasks
#32 - Add image box component (which contains a button to follow)
#74 - Add follow endpoints to the backend
#73 - Add follow button to user profile
#72 - Add a follow button to the image box component

## Acceptance Test
- Navigate to another user's page
- Display a follow/unfollow button
- Click the follow button
- If the local user is already following this user, then unfollow the user
- If the local user is not following this user, then follow the user and display "followed"

**Comment by salehatrq** [comment]
02-03-21
- Saleha: Add follow button to each user
- Christopher: Add unfollow button if the user is already followed
- Romain: Add follower count

**Comment by GryPr** [comment]
> 02-03-21
> 
> * Saleha: Add follow button to each user
> * Christopher: Add unfollow button if the user is already followed
> * Romain: Add follower count

Awesome, saw that there was a group meeting yesterday. You can add the tasks that you discussed about in the form of Github Issues.
