### ISSUE TITLE
Add a navbar that's persistent

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#31]
- Create a component for the navbar
- Make it persistent on all pages

The navbar component should be placed in App.tsx

## Steps
- Create a sitelayout component which contains the navbar (example: https://github.com/GryPr/next-experiments/blob/master/src/components/SiteLayout/SiteLayout.tsx)
- Use sitelayout in the app.tsx (example: https://github.com/GryPr/next-experiments/blob/master/src/pages/_app.tsx)

![image](https://user-images.githubusercontent.com/51273366/107127458-3a6b1480-6884-11eb-83df-3d2b894c24ea.png)

**Comment by salehatrq** [comment]
14-02-21
Added:
- Logo
- Search bar
- Home button
- Message button
