### ISSUE TITLE
Image box/post component

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#32]
It would be like the boxes on the Instagram front page

You can use placeholder text and images, we're mostly concerned with having a "template/format" created

Example: 
![image](https://user-images.githubusercontent.com/51273366/107127514-9897f780-6884-11eb-8d99-8b9e42bafd77.png)

It should have the following:
- Name of the poster
- Image
- Description

**Comment by bhattirahat** [comment]
started working on the template 
-added comment and description

**Comment by bhattirahat** [comment]
15 feb 2021 
-finished the components

**Comment by bhattirahat** [comment]
feb 18 2021
-added default avatar (placeholder)
-added default picture (placeholder)
-added the heart (clickable)

(need to add state and props)

**Comment by GryPr** [comment]
For story #30, it'd be great if you could also add a button to follow the image's creator from within the image box.
