### ISSUE TITLE
Create MongoDB connection in the backend

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#40]
- Integrate MongoDB with the API backend for image storage
- Work with @Romdefaz with #33 to set up the API so that users can post and view images that are stored in MongoDB

## Steps

1. Set up the MongoDB connection
2. Store test values in MongoDB
3. Try storing test images in MongoDB
4. TBD

## References
Follow the VSCode tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio-code

**Comment by GryPr** [comment]
Holy crap, just storing files in MongoDB that were received from an API request is very complicated. I've written experimental code in this branch: https://github.com/GryPr/SOEN341/tree/backend-mongodb-api

This is how I managed to implement storage of images received through an HTTP request in MongoDB:

We use the form-data content type to send both an image description and an image file to the backend. Afterwards, the backend can store it into MongoDB. (Code: https://github.com/GryPr/SOEN341/blob/d4b19c2ee65b9c9a07e18087f311eb1be16e981a/backend/Controllers/ImageController.cs#L50)

![image](https://user-images.githubusercontent.com/51273366/108020177-cc43f180-6fe9-11eb-9209-cc59130d6af3.png)

To store files in MongoDB, we to use GridFS which stores files in a "bucket" in binary form. We can then retrieve the file by file name. (Code: https://github.com/GryPr/SOEN341/blob/d4b19c2ee65b9c9a07e18087f311eb1be16e981a/backend/Services/ImageService.cs#L46)

**Comment by ChristopherKhoury** [comment]
Yeah, I realized. I'm working on it right now and will work on it later on today as well.
