### ISSUE TITLE
Implement image upload to React

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#44]
~~`The website should take in an image upload, and convert it to a "byte" type variable. This will then be sent inside a JSON to the backend API.~~

2021/02/17 Update:
**Description**
The API backend currently expect form-data as described here: https://github.com/GryPr/SOEN341/issues/40#issuecomment-779582335

We need to find a way to receive an image from the user through an upload button (or drag & drop), then send the image data + description to the backend using form-data.

**Objectives**
* Create code to send image files to the backend through form-data instead of JSON
* Once the API backend is complete, integrate your code with the API

**References**
~~https://stackoverflow.com/questions/40794468/upload-a-image-with-fetch~~
https://mattboldt.com/2020/05/02/formdata-with-react-hooks-and-fetch/

**Comment by GryPr** [comment]
As described here: https://github.com/GryPr/SOEN341/issues/40#issuecomment-779582335

Instead of transmitting JSON, we'd be transmitting Form-Data. It would be great if you can take a look at the Fetch API and make it send Form-Data after receiving the file from the upload button.

**Comment by Romdefaz** [comment]
Im creating a new branch, and working on it. You think its a good idea to work on the app.tsx, or should I create a new file @GryPr ?

**Comment by GryPr** [comment]
You should create your own component in the "Components" folder. "app.tsx" should only contain the bare minimum of component calls (app.tsx is the equivalent of a "main function", so we don't want to implement anything there).

**Comment by Romdefaz** [comment]
Got it! thx
