### ISSUE TITLE
Consume byte array from an API in React using fetch

### ISSUE THREAD

**Issue by GryPr** [GryPr/SOEN341#45]
**Description**
We need to consume form-data instead of JSON when receiving images through an API. This is slightly unconventional, but it seems to be the best way to do things.

**Objectives**
- Create code to consume form-data that contains both text and files (images) from within React. 
- Display the images received from form-data on the website
- Once the API backend is complete, integrate it into the website. 

**References**
This link describes sending form-data, but not necessarily receiving it. Though it should be possible to get a formdata object from the API response: https://mattboldt.com/2020/05/02/formdata-with-react-hooks-and-fetch/
Feel free to also try to find other reference material online to get this to work

**Update 2021/02/28**
Turns out that it's somewhat difficult for the backend API to send a form-data response to the frontend. For now, the backend sends a JSON to the frontend that contains a byte array with the image data.

Information and data types in the JSON:
```c#
public string FileName { get; set; } // i.e. image.jpg or image.png
public string ContentType { get; set; } // i.e. image/jpeg
public string ImageDescription { get; set; }
public DateTime CreatedOn { get; set; }
public string CreatorName { get; set; }
public byte[] ImageContent { get; set; }
```

**Comment by GryPr** [comment]
2021/02/18 Update

I've updated the original issue description with new specifications due to the API backend implementation progressing. Lmk if you have any questions about the update.

**Comment by ChristopherKhoury** [comment]
2021/02/21 Update 

Wrote the fetch api code - still working on it to finalize it.
