### ISSUE TITLE
Mocking entity framework, Unit Testing for ASP.net 

### ISSUE THREAD

**Issue by Romdefaz** [GryPr/SOEN341#84]
**Description**
Be familiar with : 
- mocking
- asp.net
- NuGet packages 
- Web API 2

**Objectives**
Model class
Create application with unit test project
adding controller
adding dependency injection
testing project with NuGet
Create bunch of tests on C#
run the tests
analyze the results

**References**
Provide links to useful reference material.

**Comment by GryPr** [comment]
Looks good, though you can take it one step at a time as follows:

1. Basic mocking in C# without ASP.NET
2. Try to mock a basic HTTP endpoint in ASP.NET (i.e. RootController's Get endpoint)
3. Try to mock the more complex endpoints

Main deliverable would be which unit testing and mocking framework you think will work best in our project, and perhaps 1 & 2 if there's time.

**Comment by Romdefaz** [comment]
sounds good! I will update the progress !
