### ISSUE TITLE
Mocking Jest framework for React frontend (TS)

### ISSUE THREAD

**Issue by bhattirahat** [GryPr/SOEN341#87]
**Description**
Be familiar with Jest,Mocking, Unit testing

**Objectives**
Being able to do unit testing for all the main components

**References**
Provide links to useful reference material.

**Comment by GryPr** [comment]
Could you add more details on what steps you'll be taking to complete the tasks? What will be the deliverables that you will produce? For example: what function will you be using Jest on, what function call will you be mocking, how will you experiment with Jest (i.e. with a test fetch call?), etc...

**Comment by GryPr** [comment]
I found a decent article on mocking fetch requests. It could be useful for unit testing image box (since you need to mock the fetch for the comments) https://jaketrent.com/post/mock-fetch-jest-test
